const mongoose = require('mongoose');

const settingsSchema = new mongoose.Schema({
  restaurantName: { type: String, default: '' },
  address:        { type: String, default: '' },
  gstin:          { type: String, default: '' },
  phone:          { type: String, default: '' },
  sgstRate:       { type: Number, default: 0 },
  cgstRate:       { type: Number, default: 0 },
  currency:       { type: String, default: '₹' },
  thankYouMsg:    { type: String, default: '' },
  darkMode:       { type: Boolean, default: true },
  directPrinting: { type: Boolean, default: false },
  qzTrayEnabled:  { type: Boolean, default: false },
  printAgentEnabled: { type: Boolean, default: false },
  printAgentPort: { type: Number, default: 5001 },
  printAgentToken: { type: String, default: '' },
  kitchenPrinterName: { type: String, default: '' },
  barPrinterName: { type: String, default: '' },
  billingPrinterName: { type: String, default: '' },
  detectedPrinters: { type: [String], default: [] },
  upiId:          { type: String, default: '' },
  includeUpiAmount: { type: Boolean, default: true },
  adminEmail:     { type: String, default: '' },
  senderEmail:    { type: String, default: '' },
  senderPassword: { type: String, default: '' },
  inventoryCategories: { type: [String], default: ['Spirits','Beer','Wine','Food','Mixers'] },
  menuCategories:      { type: [String], default: ['Spirits','Beer','Wine','Food','Mixers'] },
  googleReviewLink:    { type: String, default: '' },
  instagramLink:       { type: String, default: '' },
  facebookLink:        { type: String, default: '' },
  whatsappEnabled:     { type: Boolean, default: false },
  whatsappTemplate:    { type: String, default: 'Thank you for dining with us, {customerName}! Your bill no. is {billNo} for {grandTotal}. Please share your review here: {googleReviewLink}. Follow us on Instagram: {instagramLink} and Facebook: {facebookLink}' },
}, { timestamps: true });

module.exports = mongoose.model('Settings', settingsSchema);
